### ISSUE TITLE
ValueError: could not broadcast input array from shape (51,6) into shape (50,6)

### ISSUE THREAD

**Issue by Amitdutta121** [mymusise/Trading-Gym#2]
How to fix this? I run the Example(train_fake.py) file with parameter of True & True

Traceback (most recent call last):
  File "C:/Users/amit/PycharmProjects/dqnTrading/train_fake.py", line 40, in <module>
    test_fake(True, True)
  File "C:/Users/amit/PycharmProjects/dqnTrading/train_fake.py", line 30, in test_fake
    'learning_rate': 5e-5
  File "C:\Users\amit\PycharmProjects\dqnTrading\base.py", line 111, in train
    model.learn(total_timesteps=train_steps, callback=self.callback)
  File "C:\Users\amit\venv\new\lib\site-packages\stable_baselines\deepq\dqn.py", line 180, in learn
    obs = self.env.reset()
  File "C:\Users\amit\venv\new\lib\site-packages\stable_baselines\common\base_class.py", line 765, in reset
    return self.unvec_obs(self.venv.reset())
  File "C:\Users\amit\venv\new\lib\site-packages\stable_baselines\common\vec_env\dummy_vec_env.py", line 50, in reset
    self._save_obs(env_idx, obs)
  File "C:\Users\amit\venv\new\lib\site-packages\stable_baselines\common\vec_env\dummy_vec_env.py", line 69, in _save_obs
    self.buf_obs[key][env_idx] = obs
ValueError: could not broadcast input array from shape (51,6) into shape (50,6)

**Comment by mymusise** [comment]
Thanks for your feedback. 
I am sorry that there's no `Windows` arround me, I only test it on Linux(Ubuntu 16.04+).
Have a try run it on Linux.
